version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    restart: always
    networks:
      - blog-network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: CHANGE_ME
      POSTGRES_PASSWORD: CHANGE_ME
    ports:
      - "5432:5432"
    restart: always
    networks:
      - blog-network
    volumes:
      - postgres-blog-data:/var/lib/postgresql

networks:
  blog-network:
    driver: bridge

volumes:
  postgres-blog-data: